import { event, recorder, container } from 'codeceptjs';
import * as fs from 'node:fs';
import * as path from 'node:path';

/**
 * ============================================================================
 * Failure Artifacts Plugin for Allure 3
 * ============================================================================
 *
 * Automatically attaches Playwright failure recordings (.webm video and .zip trace)
 * directly to the Allure test result when a test fails.
 *
 * Screenshots on failure are natively attached via the `screenshotOnFail` plugin.
 * This plugin complements it by ensuring failure videos and traces are also
 * viewable and playable directly inside the Allure Report UI.
 */
export default function failureArtifacts(options: { enabled?: boolean } = {}) {
  if (options.enabled === false) return;

  event.dispatcher.on(event.test.after, (test: any) => {
    if (!test || test.state !== 'failed') return;

    recorder.add('attach failure video and trace to allure', async () => {
      try {
        const allure = container.plugins('allure');
        if (!allure || typeof allure.addAttachment !== 'function') return;

        // 1. Attach Video Recording if generated by Playwright on failure
        const videoPath = test.artifacts?.video;
        if (videoPath) {
          // Wait up to 3 seconds for Playwright to finish saving the webm stream to disk
          for (let i = 0; i < 30; i++) {
            if (fs.existsSync(videoPath) && fs.statSync(videoPath).size > 0) break;
            await new Promise((resolve) => setTimeout(resolve, 100));
          }

          if (fs.existsSync(videoPath) && fs.statSync(videoPath).size > 0) {
            const videoContent = fs.readFileSync(videoPath);
            allure.addAttachment(
              `Execution Video (${path.basename(videoPath)})`,
              videoContent,
              'video/webm',
            );
          }
        }

        // 2. Attach Playwright Trace if generated on failure
        const tracePath = test.artifacts?.trace;
        if (tracePath && fs.existsSync(tracePath)) {
          const traceContent = fs.readFileSync(tracePath);
          allure.addAttachment(
            `Playwright Trace (${path.basename(tracePath)})`,
            traceContent,
            'application/zip',
          );
        }
      } catch (err) {
        console.warn('[FailureArtifacts] Warning attaching failure video/trace to Allure:', err);
      }
    }, true);
  });
}
